#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

ln -sf $SCRIPT_DIR/gitconfig $HOME/.gitconfig
ln -sf $SCRIPT_DIR/gitignore-global $HOME/.gitignore-global

echo "Git sorted, yo."
