#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

for ARG in "$@"
do
    if [ $ARG = "bash" ] || [ $ARG = "all" ]
    then
        ln -sf $SCRIPT_DIR/bash/bashrc $HOME/.bashrc

        echo "bash config done"
    fi

    if [ $ARG = "git" ] || [ $ARG = "all" ]
    then
        ln -sf $SCRIPT_DIR/git/gitconfig $HOME/.gitconfig
        ln -sf $SCRIPT_DIR/git/gitignore-global $HOME/.gitignore-global

        echo "Git config done"
    fi

    if [ $ARG = "mac" ] || [ $ARG = "all" ]
    then
        source $SCRIPT_DIR/macos/mac_defaults.sh

        echo "Mac config done"
    fi

    if [ $ARG = "ssh" ] || [ $ARG = "all" ]
    then
        ln -sf $SCRIPT_DIR/ssh/config $HOME/.ssh/config
    
        echo "SSH config done"
    fi

    if [ $ARG = "zsh" ] || [ $ARG = "all" ]
    then
        ln -sf $SCRIPT_DIR/zsh/zshrc $HOME/.zshrc

        echo "zsh config done"
    fi
done
